### ISSUE TITLE
Does this library support writting dbf?

### ISSUE THREAD

**Issue by sinall** [sharazam/dbflib#1]
I didn't find any write method in `DBaseFile.h`.

**Comment by fschutt** [comment]
No, it doesn't support writing. I wrote this software as a learning experience to learn C++ in 2016 (and to read some DBF files from the company I worked at). I just put it on GitHub as a backup, it's not really maintained or supported. Feel free to fork it or look through the source code yourself. It's likely not very high quality, expect undergrad-level mistakes.

Since then I've switched to Rust because C++ dependency management is an absolute pain. If you want my advice: use [dbf-extractor](https://crates.io/crates/dbf_dextractor) from Rust, [compile the code into a C DLL](https://doc.rust-lang.org/nomicon/ffi.html#calling-rust-code-from-c), write the corresponding C header bindings and link your code from C / C++. That's how I'd do it now if I had to support an existing C / C++ project. Dependency management and setting up external dependencies is just such a pain in C++.
